### ISSUE TITLE
Error at startup in version 0.7.0

### ISSUE THREAD

**Issue by jacekpaszkowski** [bieniu/ha-gios#10]
After update to version 0.7.0 i get this error and component doesn't seem to work any more.

```
2020-01-15 15:21:13 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry GIOŚ for gios
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 192, in async_setup
    hass, self
  File "/config/custom_components/gios/__init__.py", line 34, in async_setup_entry
    if config_entry.unique_id is None:
AttributeError: 'ConfigEntry' object has no attribute 'unique_id'
```

**Comment by bieniu** [comment]
Please look at the changelog.
