### ISSUE TITLE
state error

### ISSUE THREAD

**Issue by reaper7** [bieniu/ha-gios#4]
I get this error:
```
Traceback (most recent call last):
  File "/home/pi/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/home/pi/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
    self._async_write_ha_state()
  File "/home/pi/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 300, in _async_write_ha_state
    state = self.state
  File "/home/pi/.homeassistant/custom_components/gios/sensor.py", line 163, in state
    self._state = round(self._state)
TypeError: type NoneType doesn't define __round__ method
```

**Comment by bieniu** [comment]
Fixed via https://github.com/bieniu/ha-gios/releases/tag/0.3.2

**Comment by reaper7** [comment]
indeed, works great :)
tnx!
