### ISSUE TITLE
Error in logs but all sensors have value

### ISSUE THREAD

**Issue by jacekpaszkowski** [bieniu/ha-gios#6]
Hi,

every ~30 seconds i get this kind of error in HA logs:

`2019-09-25 13:38:51 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 300, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/gios/sensor.py", line 169, in state
    self._state = self.gios.sensors[self.kind][ATTR_VALUE]
KeyError: 'value'`

But sensors have values.

BTW thank you for great work and this GIOS component :)

Regards,
Jacek

**Comment by jacekpaszkowski** [comment]
yes version 0.4.2, i use station 552

**Comment by bieniu** [comment]
GIOS server is very unstable for several days. [This](https://github.com/bieniu/ha-gios/releases/tag/0.4.3) should fix that issue.

**Comment by jacekpaszkowski** [comment]
Ok i see. Thanks for updated version!
